// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gacha.proto

package gacha

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Card struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_gacha_b3d9850b58e97881, []int{0}
}
func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (dst *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(dst, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Cards                []*Card  `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_gacha_b3d9850b58e97881, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Response struct {
	Card                 *Card    `protobuf:"bytes,1,opt,name=card" json:"card,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_gacha_b3d9850b58e97881, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *Response) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*Card)(nil), "gacha.Card")
	proto.RegisterType((*Request)(nil), "gacha.Request")
	proto.RegisterType((*Response)(nil), "gacha.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GachaClient is the client API for Gacha service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GachaClient interface {
	Lottery(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type gachaClient struct {
	cc *grpc.ClientConn
}

func NewGachaClient(cc *grpc.ClientConn) GachaClient {
	return &gachaClient{cc}
}

func (c *gachaClient) Lottery(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gacha.Gacha/Lottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gacha service

type GachaServer interface {
	Lottery(context.Context, *Request) (*Response, error)
}

func RegisterGachaServer(s *grpc.Server, srv GachaServer) {
	s.RegisterService(&_Gacha_serviceDesc, srv)
}

func _Gacha_Lottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaServer).Lottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gacha.Gacha/Lottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaServer).Lottery(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gacha_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gacha.Gacha",
	HandlerType: (*GachaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lottery",
			Handler:    _Gacha_Lottery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gacha.proto",
}

func init() { proto.RegisterFile("gacha.proto", fileDescriptor_gacha_b3d9850b58e97881) }

var fileDescriptor_gacha_b3d9850b58e97881 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4f, 0x4c, 0xce,
	0x48, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xa4, 0xb8, 0x58, 0x9c,
	0x13, 0x8b, 0x52, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0x6c, 0x25, 0x1d, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x45, 0x2e, 0xd6, 0xe4, 0xc4, 0xa2, 0x94, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x6e,
	0x3d, 0x88, 0x51, 0x20, 0xad, 0x41, 0x10, 0x19, 0x25, 0x37, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x79, 0x2e, 0x16, 0x90, 0x20, 0xd8, 0x34, 0x34, 0xd5, 0x60, 0x09,
	0x21, 0x49, 0x2e, 0x8e, 0xa2, 0xd4, 0x92, 0xf8, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xd6, 0x20, 0xf6, 0xa2, 0xd4, 0x12, 0xe7, 0xfc, 0x94, 0x54, 0x23, 0x53, 0x2e, 0x56, 0x77,
	0x90, 0x72, 0x21, 0x1d, 0x2e, 0x76, 0x9f, 0xfc, 0x92, 0x92, 0xd4, 0xa2, 0x4a, 0x21, 0x3e, 0xa8,
	0x09, 0x50, 0xe7, 0x48, 0xf1, 0xc3, 0xf9, 0x10, 0x0b, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xde, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x4f, 0x6d, 0x85, 0xe5, 0x00, 0x00, 0x00,
}
